server:
  port: 8070
spring:
  application:
    name: Sanbox
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  sql:
    init:
      mode: always
  config:
    import: "configserver:http://127.0.0.1:8888"
  cloud:
    config:
      profile: dev
      name: config

logging:
  level:
    com.jk.sandbox: debug
    org.springframework.web.servlet: debug
