spring:
  application:
    name: board
  datasource:
    url: jdbc:mysql://localhost:3308/board
    username: board
    password: board
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
